controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - waist
      - shoulder
      - elbow
      - wrist_angle
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - left_finger
      - right_finger
initial:  # Define initial robot poses per group
  - group: arm
    pose: home
  - group: gripper
    pose: Closed